/*
 * Purpose       : Write Class When
 * 
 * Created By    : Nikunj jain
 * 
 * Created Date  : 25-03-2023
 * 
 * Revision Log  :
 * 
 * Trigger to First create two fields on CONTACT object paid amount(currency) and sequential number(number) 
   And now according to paid amount give them sequential number do this with the help of trigger.
*/
public Without Sharing class ContactTriggerHandler_Test {

}